import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next App</h1>
        <Link href="/todolist">Todo List</Link>
        <Link href="/todolist/addTask">addTask</Link>
      </main>
    </>
  );
}
